# Generated by Django 5.1.4 on 2025-04-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsApp', '0002_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
                ('horario', models.CharField(blank=True, max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden'],
            },
        ),
    ]
