# Generated by Django 5.1.4 on 2025-04-20 00:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsApp', '0003_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='contenido_detallado',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido Detallado'),
        ),
    ]
