# Generated by Django 5.1.4 on 2025-04-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsApp', '0004_evento_contenido_detallado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título que aparecerá sobre la imagen', max_length=100)),
                ('subtitulo', models.CharField(help_text='Subtítulo o descripción corta', max_length=200)),
                ('imagen', models.ImageField(help_text='Imagen para el carrusel (recomendado: 1920x1080px)', upload_to='carousel/')),
                ('orden', models.IntegerField(default=0, help_text='Orden en que aparecerá la imagen (menor número = primero)')),
                ('activo', models.BooleanField(default=True, help_text='Determina si la imagen se muestra en el carrusel')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imagen del Carrusel',
                'verbose_name_plural': 'Imágenes del Carrusel',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
    ]
