# Generated by Django 5.1.4 on 2025-04-27 14:41

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsApp', '0005_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', CKEditor5Field(verbose_name='Objetivo', config_name='extends')),
                ('mision', CKEditor5Field(verbose_name='Misión', config_name='extends')),
                ('vision', CKEditor5Field(verbose_name='Visión', config_name='extends')),
                ('historia', CKEditor5Field(verbose_name='Historia', config_name='extends')),
                ('activo', models.BooleanField(default=True, help_text='Solo debe haber un registro activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información Institucional',
                'verbose_name_plural': 'Información Institucional',
            },
        ),
    ]
