# Generated by Django 5.1.4 on 2025-04-27 16:37

import eventsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsApp', '0006_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='imagen',
            field=models.ImageField(help_text='Imagen para el carrusel (recomendado: 1920x1080px). Máximo 5MB. Formato recomendado: JPG', upload_to='carousel/', validators=[eventsApp.models.validate_carousel_image_size]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Máximo 2MB. Formato recomendado: JPG o PNG', null=True, upload_to='team/', validators=[eventsApp.models.validate_team_image_size]),
        ),
    ]
